### ISSUE TITLE
Error when using with Liferay CMS

### ISSUE THREAD

**Issue by gilesw** [pivotalsoftware/session-managers#40] opened 2017-05-23 09:36 UTC
I'm getting this error using the session manager with Liferay CMS. I suspect it's due to the content of the session not being serialisable as I've hit the same problem with another session manager. Any ideas how I might debug this? 

```
May 23, 2017 8:23:40 AM com.gopivotal.manager.redis.RedisStore logAndCreateEmptySession
SEVERE: Unable to load session D09837183B2E37AA5000CE99CCF5500E. Empty session created.
java.lang.ClassNotFoundException: com.liferay.portlet.PortalPreferencesImpl
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:278)
        at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:625)
        at com.gopivotal.manager.SessionSerializationUtils$1.resolveClass(SessionSerializationUtils.java:71)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1619)
        at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1084)
        at com.gopivotal.manager.SessionSerializationUtils.deserialize(SessionSerializationUtils.java:77)
        at com.gopivotal.manager.redis.RedisStore$20$1.invoke(RedisStore.java:484)
        at com.gopivotal.manager.redis.RedisStore$20$1.invoke(RedisStore.java:475)
        at com.gopivotal.manager.redis.JedisTemplate.withJedis(JedisTemplate.java:41)
        at com.gopivotal.manager.redis.RedisStore$20.invoke(RedisStore.java:475)
        at com.gopivotal.manager.redis.RedisStore$20.invoke(RedisStore.java:468)
        at com.gopivotal.manager.LockTemplate.withReadLock(LockTemplate.java:59)
        at com.gopivotal.manager.redis.RedisStore.load(RedisStore.java:468)
        at org.apache.catalina.session.PersistentManagerBase.swapIn(PersistentManagerBase.java:747)
        at org.apache.catalina.session.PersistentManagerBase.findSession(PersistentManagerBase.java:511)
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2987)
        at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2605)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:430)
        at com.gopivotal.manager.SessionFlushValve$7.invoke(SessionFlushValve.java:163)
        at com.gopivotal.manager.SessionFlushValve$7.invoke(SessionFlushValve.java:158)
        at com.gopivotal.manager.LockTemplate.withReadLock(LockTemplate.java:59)
        at com.gopivotal.manager.SessionFlushValve.invoke(SessionFlushValve.java:158)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by gilesw** [comment] 2017-05-24 09:58
I managed to dump a session but I'm not sure how to decode it / what part may contain credentials so I'm not posting here.

I did get the clustering to work using the built in delta manager. Which I'm surprised at given that it's also not supposed to work with non-serialisable content.

**Comment by ccheetham** [comment] 2017-05-24 12:48
Based on trace, this appears to be a 1.2.x session manager release.  Which release of Tomcat?

**Comment by ccheetham** [comment] 2017-05-24 18:14
I was able to replicate using Tomcat 8.0.42 and redis store 1.2.x.

It's a bug in how objects are deserialized in the redis store impl.  It was partly addressed for Tomcat 7 but (evidently) not for Tomcat 8.

This is in a class of problems related to changes in Tomcat APIs and practices from 7->8->85->9.

The specifics for this particular bug are evident in the following impls in Tomcat 7 and 8 (similar diffs for 85 and 9).  Check out the `load(String id)` impls:
http://svn.apache.org/repos/asf/tomcat/tc7.0.x/trunk/java/org/apache/catalina/session/FileStore.java 
http://svn.apache.org/repos/asf/tomcat/tc8.0.x/trunk/java/org/apache/catalina/session/FileStore.java

We've addressed this class of issues in in a 2.0 branch yet to be pushed to the main repo in which there are different code bases for Tomcat 7/8/85/9 albeit in a single code branch.  You can see a preview at:
https://github.com/ccheetham/session-managers/tree/2.0.x/tomcat/src/main

It'll be a little bit of time before we push this for general release.  However I can make a diff to the main repo's 1.2.x branch available with the fix for Tomcat 8 upon request.

**Comment by gilesw** [comment] 2017-05-25 10:03
Liferay 6.2.x is bundled with tomcat7 so my hands are tied there really, hopefully I'll get time to try out your patch because I hate this delta manager because I have to specify the cluster in a static way and do nasty things like remove the local node from that cluster list:-

```
{% for host in liferay_cluster_hosts %}
  {% if host.name != inventory_hostname %}
    <Member className="org.apache.catalina.tribes.membership.StaticMember" host="{{ host.name }}" port="4444" uniqueId="{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,{{ host.id}}}"/>
  {% endif %}
{% endfor %}
```

```
liferay_cluster_hosts:
  - name: devperf01a
    id: 1
  - name: devperf01e
    id: 2
```

**Comment by gilesw** [comment] 2017-05-25 11:03
@ccheetham I pulled your repo and changed to that branch and ran a build with:-

```
(2.0.x):~/work/session-managers ./gradlew assemble -PtomcatVersion=7
:common:compileJava NO-SOURCE
:common:processResources NO-SOURCE
:common:classes UP-TO-DATE
:common:jar UP-TO-DATE
:common:assemble UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1.809 secs

-rw-r--r-- 1 xxxx xxx 261 May 25 11:57 ./common/build/libs/pivotal-tomcat-session-manager-2.0-SNAPSHOT.jar

```
However I get a failure on startup with class not found on the flush class.

**Comment by gilesw** [comment] 2017-05-25 11:55
@ccheetham I built the tomcat7 version from your branch on and it generated these files:-

./jedis/build/libs/pivotal-session-stores-tomcat7-jedis-2.0-SNAPSHOT-all.jar
./jedis/build/libs/pivotal-session-stores-tomcat7-jedis-2.0-SNAPSHOT.jar
./tomcat/build/libs/pivotal-session-stores-tomcat7-2.0-SNAPSHOT.jar

however I'm getting an error on startup using:
```

        <Manager className="org.apache.catalina.session.PersistentManager">
            <Store
                className="com.gopivotal.manager.redis.RedisStore"
                connectionPoolSize="20"
                host="devplay01e"
            />
        </Manager>
```

do I have the wrong classname?

**Comment by gilesw** [comment] 2017-05-25 12:10
Okay I grabbed the new classnames:

   ```
     <Valve className="io.pivotal.appsuite.tomcat.v7.Tomcat7SessionFlushValve" />
        <Manager className="org.apache.catalina.session.PersistentManager">                                                                                                                   <Store                                                                                                                                                                                className="io.pivotal.appsuite.tomcat.jedis.RedisStore"
                connectionPoolSize="20"
                host="devplay01e"
            />
        </Manager>
```
However I'm getting an error with the flush class:

12:04:37,685 WARN  [http-bio-8080-exec-6][code_jsp:130] {code="500", msg="", ```
uri=/combo/}
java.lang.NullPointerException
        at io.pivotal.appsuite.tomcat.SessionFlushValve.invoke(SessionFlushValve.java:79)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)


```

**Comment by ccheetham** [comment] 2017-05-25 12:14
I'd avoid that branch for now, I've not had a whole lot of test cycles on it.  It's also missing a few features such as JMX and property notification.

I pushed a branch off of 1.2.x containing the the specific fix for Tomcat 8 at ccheetham/session-managers@f3cb4f6.

**Comment by gilesw** [comment] 2017-05-25 12:17
I'm getting the same error as before just with a different message:-

`SEVERE: Error deserializing Session 4BCC7FE66285EC121A6EB3EB1FBCC367: {1}                                                                                                         java.lang.ClassNotFoundException: com.liferay.portlet.PortalPreferencesImpl`

**Comment by ccheetham** [comment] 2017-05-25 12:18
Which version of Tomcat are you using?

**Comment by gilesw** [comment] 2017-05-25 12:30
I'm using Tomcat7 which is what Liferay is bundled with. I doubt I can use 8 without losing commercial support.

**Comment by gilesw** [comment] 2017-05-25 12:44
I just tried another manager and got a very specific error:-

`java.lang.ClassCastException: java.lang.Long cannot be cast to com.orangefunction.tomcat.redissessions.SessionSerializationMetadata`

**Comment by ccheetham** [comment] 2017-05-25 13:49
Apologies on the Tomcat version.  I was able to reproduce using Tomcat 7.  Pushed a fix to ccheetham/session-managers@c99a3a0 to branch 1.2.x-tomcat7.

**Comment by gilesw** [comment] 2017-05-25 14:58
@ccheetham I ran mvn package but the build libs don't appear to include sl4j

```
SEVERE: Begin event threw error
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.gopivotal.manager.StandardLifecycleSupport.<init>(StandardLifecycleSupport.java:32)
```
However Liferay does include sl4j so I dropped that jar into the tomcat libs dir.

**Comment by ccheetham** [comment] 2017-05-25 15:31
They're left out in case someone wants to use a different log backend.  (Prob should doc that.)

**Comment by gilesw** [comment] 2017-05-25 15:32
@ccheetham this /appears/ to work! I'm just running some tests now. The only problem I can see is that when I logout in Liferay no Redis keys are deleted. However if I re-login with the same browser session, no new keys are created either. Is this expected behaviour?

**Comment by gilesw** [comment] 2017-05-25 15:33
For logging to work do I need to drop in log4j as well as slf4j then?

**Comment by ccheetham** [comment] 2017-05-25 16:02
In addition the SLF4J API jar, you need to add a SLF4J binding. 
 Tomcat uses `java.util.logging` so that's the binding you probably want.

```
% ls -1 lib
redis-store-1.2.3.BUILD-SNAPSHOT.jar   # redis store
slf4j-api-1.7.25.jar                   # SLF4J API
slf4j-jdk14-1.7.25.jar                 # SLF4J binding to java.util.logging
```

**Comment by gilesw** [comment] 2017-05-25 16:52
:( so not having slf4j-jdk14-1.7.25.jar meant the errors were being swallowed. Still getting the same empty session warnings being created with this patched jar.

I'm wondering if I'm chasing the wrong thing. I wanted all portlets to share the same session id so I've set this global context:-

<Context sessionCookiePath="/" crossContext="true" >

The root context application has this set in the web.xml too <distributable/>

**Comment by gilesw** [comment] 2017-05-25 16:54
The manager is getting loaded for each portlet too.

**Comment by ccheetham** [comment] 2017-05-25 17:08
I'm not familiar with Liferay, but may be able to set one up and give it a go. 

WRT to original question about the class not being serializable, Tomcat should ignore non-serializable attribute values so I don't think that's the cause.  It looks like the context in which this particulate deserialization is occurring does not have access the the class.

**Comment by ccheetham** [comment] 2017-05-26 16:53
This may be by design.

Installed Liferay CE 6.2, found the class that can't be loaded:

```
tomcat-7.0.62/webapps/ROOT/WEB-INF/lib/portal-impl.jar
    com/liferay/portlet/PortalPreferencesImpl.class
```

So that class is part of the `/` (ROOT) context.

When the home page is loaded, there are GETs to the `notification-portlet` which trigger the class not found exception.  The `notification-portlet` does not include that class in its `WEB-INF`.

**Comment by ccheetham** [comment] 2017-05-26 17:41
You can try to configure the session persistence/valve for just the ROOT context.

For example, move the valve and redis store config from `conf/context.xml` to `conf/Catalina/localhost/ROOT.xml`:

```
% cat conf/Catalina/localhost/ROOT.xml
<Context path="" crossContext="true">
  <Valve className="com.gopivotal.manager.SessionFlushValve" />
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="com.gopivotal.manager.redis.RedisStore" />
  </Manager>
</Context>
```

**Comment by gilesw** [comment] 2017-05-27 21:24
@ccheetham much appreciate your help. I'm off for a few days but when I get back I'll certainly give this a go. What I'd like to know is what gets put into these sessions and by which portlet. I'm normally just dealing with single spring applications loaded into a root context. I've used a different session store which also failed with Liferay..

https://github.com/magro/memcached-session-manager/issues/351

**Comment by gilesw** [comment] 2017-06-02 13:54
@ccheetham so I've added the manager to only the root context and I'm not getting any errors and sessions appear to be working. My concern is whether there are other contexts that are now only writing to local in memory sessions but at moment this looks closable as not a bug..

**Closed** 2021-01-07 21:34 UTC
Labels: bug
